flowchart TD
    Start(("Main Start")) --> createForest(("Create New Forest"))
    createForest --> p1["Clear Screen"]
    p1 --> p2["Initalize While Loop"]
    p2 --> displayForest(("displayForest"))
    displayForest --> p3@{ label: "Initalize 'nextForest' dictionary" }
    p3 --> p4["For each x,y in nextForest"]
    d4{"does x,y already exist"} -- no --> d1{"is x,y EMPTY and RAND &lt;= GrowChance"}
    d1 -- no --> d2{"is x,y TREE and RAND &lt;= FireChance"}
    d2 -- no --> d3{"is x,y FIRE"}
    d3 -- no --> p5["Set x,y to same value as last forest"]
    d4 -- yes --> p11{"All x,y done?"}
    d1 -- yes --> p6["Set x,y to TREE"]
    d2 -- yes --> p7["Set x,y to FIRE"]
    p5 --> p11
    p6 --> p11
    p7 --> p11
    p8["Set x,y to EMPTY"] --> p11
    d8{"neighbor Cell= Tree?"} -- Yes --> p9["Set neighbor to FIRE"]
    p9 --> n2["Done Iterating NeigborCells?"]
    p11 -- no --> p4
    p11 -- yes --> p12["Sleep"]
    p12 --> displayForest
    io1[/"Press Cntr-C"/] --> End(("Exit"))
    n1["For Each Neighbor Cell"] --> d8
    n2 -- No --> n1
    n2 -- YEs --> p8
    d3 -- Yes --> n1
    d8 -- No --> n2
    p4 --> d4

    p3@{ shape: rect}
    n2@{ shape: diam}
    n1@{ shape: rect}
     Start:::terminatorStart
     createForest:::terminatorStart
     p1:::process
     p2:::process
     displayForest:::terminatorStart
     p3:::process
     p4:::process
     d4:::decision
     d1:::decision
     d2:::decision
     d3:::decision
     p5:::process
     p11:::decision
     p6:::process
     p7:::process
     p8:::process
     d8:::decision
     p9:::process
     n2:::decision
     p12:::process
     io1:::inputOutput
     End:::terminatorFinish
     n1:::process
    classDef database fill:#ffeb3b,stroke:#333,color:#000
    classDef inputOutput fill:#9933cc,stroke:#333,color:#fff
    classDef terminatorStart fill:#4CAF50,stroke:#333,color:#fff
    classDef terminatorFinish fill:#F44336,stroke:#333,color:#fff
    classDef process fill:#0066cc, stroke:#333, color:#fff
    classDef decision fill:#ff9900, stroke:#333, color:#fff
